version: '2'

services:

### Nginx Server Container ##################################
    nginx:
        restart: always
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        links:
            - php-fpm
        environment:
            - VIRTUAL_HOST=tasks.dev

### PHP-FPM Container #######################################

    php-fpm:
        restart: always
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
            dockerfile: Dockerfile-56
        volumes_from:
            - volumes_source
        expose:
            - "9000"

    cron:
        restart: always
        build:
            context: ./cron
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
            dockerfile: Dockerfile-56
        volumes_from:
            - volumes_source

### MySQL Container #########################################

    mysql:
        restart: always
        build: ./mysql
        volumes:
            - ../db/mysql:/var/lib/mysql
            - ../db/backup:/var/www/backup
        environment:
            MYSQL_DATABASE: site
            MYSQL_USER: site
            MYSQL_PASSWORD: site
            MYSQL_ROOT_PASSWORD: root
        expose:
            - "3306"

### Nodejs Container ##################################
    node:
        restart: always
        build:
             context: ./node
             args:
                 - INSTALL_NODE=true
        volumes_from:
            - volumes_source

### Application Code Container ##############################

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../source/:/var/www/site

networks:
    default:
        external:
            name: nginx-proxy