// APP
export const APP_NAME='Задачи';

// API
export const API='/api/v1';
export const API_KEY='';

// SUCCESS
export const SUCCESS_FETCH_TASKS='SUCCESS_FETCH_TASKS';
export const SUCCESS_FETCH_TASK='SUCCESS_FETCH_TASK';
export const SUCCESS_STORE_TASK='SUCCESS_STORE_TASK';
export const SUCCESS_UPDATE_TASK='SUCCESS_UPDATE_TASK';
export const SUCCESS_DELETE_TASK='SUCCESS_DELETE_TASK';